name: 'repo2docker Action'
description: 'Creates a docker image of your repository to view the collection of notebooks'
inputs:
  NOTEBOOK_USER:
    description: username of the primary user in the image
    require: false
  IMAGE_NAME:
    description: name of the image.  Example - myContainer
    require: true
outputs:
  CURR_DOCKER_VER:
    description: The docker version used to build
  CURR_CONDA_VER:
    description: The conda version used to build
  CURR_R2D_VER:
    description: The repo2docker version used to build
runs:
  using: 'docker'
  image: 'Dockerfile'
