name: 'repo2docker Action'
description: 'Creates a docker image of your repository to view the collection of notebooks'
inputs:
  IMAGE_NAME:
    description: name of the image.  Example - myContainer
    require: true
  NOTEBOOK_USER:
    description: username of the primary user in the image
    require: false
outputs:
  IMAGE_SHA_NAME:
    description: The name of the docker image, which is tagged with the SHA.
runs:
  using: 'docker'
  image: 'Dockerfile'
